_base_: "racc_grid4x4_v7_reconstruction.yaml"
experiment_name: "racc_grid4x4_v8_uncertainty"

dynamic_graph:
  reconstruction_coef: 1.0
  confidence_coef: 0.5
  counterfactual_coef: 0.0
  counterfactual_samples: 0
